### ISSUE TITLE
Error 500 al contactar

### ISSUE THREAD

**Issue by javierreraul** [UNIZAR-30226-2020-09/Backend#41]
**Remitente:** _javierreraul@gmail.com_
**Mensaje:** _L avefd ad es que la apsfi +frsñ+sçq421412 fsakfjaskfjaslkfjoi349asfsafasfasfasfasfiasjfhaslkfjaslkfjaslofasjflñsajflksñajfaslñofkjaslfkaslfkasflñaskflaskfslañkfsalkaslfasklfaskfaslñfkaslñfkaslñfkaslfskalfkaslñfaskf amejorad la api backend asfpasfpoasujofplñkaskjloñkfsakflñsakfalsñfkaslñfkjmaslfkaslñfkasakslfsaklñfasjflñaskflasf que ya os vale ofuasf pasuofp9182394128491204812948219482194 8asofjaslfksalñfaskjf903'2148129048124'90128940'129402194012'941'024912'049120'491204912'04921'04912'049210'49210'4921'04912'0941204921041294fpsakxf,asf_

**Comment by Aleparicio** [comment]
Los mensajes están limitados actualmente a 255 caracteres, no es un bug es una limitado consciente y controlada, deberíamos poder modificarlo sin demasiado problema si juzgas que es necesario. Con los demás formularios ocurre lo mismo, pero ya se ha limitado la longitud de mails y passwords en el frontend.
