### ISSUE TITLE
En la peti listar me llegan contras con categoria compartida id 212 (rol 0) y con categoria compartida id 191 (rol 1), en la peti listar grupal me llegan contras con categoria compartida id -1. Al listar categorías del usuario solo aparece la 191, esto es un problema para filtrar por categoría.

### ISSUE THREAD

**Issue by sergioge99** [UNIZAR-30226-2020-09/Backend#65]
![testing_group_1-3](https://user-images.githubusercontent.com/47826259/81498895-d5b86480-92c7-11ea-898b-48990db8a128.png)

**Comment by alexx99gg** [comment]
He hecho que "/api/grupo/listar" de solo las que hayan sido compartidas para tí (no eres el dueño / rol=0)

No veo problema en filtrar por categoría compartida, ya que tenéis un desplegable exclusivo para estas, no obstante os lo añado en la petición de obtener categorías
