### ISSUE TITLE
Redes Sociales -> Redes sociales (para que sea coherente con el resto)

### ISSUE THREAD

**Issue by javierreraul** [UNIZAR-30226-2020-09/Backend#71]
Si cuesta mucho o va a requerir tirar la base de datos... Haz un wontfix

![image](https://user-images.githubusercontent.com/56364932/81969816-d2eaa600-961e-11ea-89a7-1e0a384a138b.png)

**Comment by Aleparicio** [comment]
Puedo tratar de modificarlo para los nuevos usuarios y repasar el par de categorías con ese nombre ya creadas para ponerles la minúscula a mano y evitar tirar la bbdd.
