### ISSUE TITLE
Recuperación de acceso a cuenta en 2FA no funciona

### ISSUE THREAD

**Issue by JesusAngelGonzalez** [UNIZAR-30226-2020-09/Backend#74]
El codigo se recibe bien al correo. Si introduces mal el codigo o la contraseña es la misma lo notifica correctamente, pero cuando todo esta correcto no hace nada, ni mensaje de error, ni correcto, ni crasheo...

**Comment by javierreraul** [comment]
A mí me ha funcionado la recuperación de acceso a la cuenta sin ningún problema :/

/cc @alexx99gg @JesusAngelGonzalez @raulrhs @Aleparicio

**Comment by JesusAngelGonzalez** [comment]
Ya funciona con la nueva version del 2FA
